Added carousel role description
eBay/ebayui-core pull request #1222
Opened 2020-09-03 17:20 UTC by agliga

## Description
Added role description. Will generate an ID used for `aria-labelledby` on the root. This ID is only available when there is a clipped text (`a11yStatusText or `a11yHeadingText`, or is `discrete`).
Added `role="group"` and `aria-roledescription="carousel"`

## References
#609

2020-09-03 20:37 UTC, ianmcburnie requested changes
Good news: the `aria-roledescription` change negates the need for appending the carousel title to each paddle, as the screen reader now automatically announces the roledescription (carousel) and label (top products).

Bad news: you'll need to revert the changes to paddle as it results in carousel and top products being announced twice  :-)

Also, we should remove any mention of the word carousel from our a11y text examples, as this is now handled by the screen reader via the roledescription value.

2020-09-03 21:56 UTC, agliga commented
> Good news: the `aria-roledescription` change negates the need for appending the carousel title to each paddle, as the screen reader now automatically announces the roledescription (carousel) and label (top products) when focus first moves inside the carousel group.
> 
> Bad news: you'll need to revert the changes to paddle as it results in carousel and top products being announced twice :-)
> 
> Also, we should remove any mention of the word carousel from our a11y text examples, as this is now handled by the screen reader via the roledescription value.

Done, reverted the change. Also I removed ` - carousel` from the default text

2020-09-04 04:19 UTC, ianmcburnie commented
Updates look good, but for some reason the first few examples don't have the ARIA attributes:

![Screen Shot 2020-09-03 at 9 18 31 PM](https://user-images.githubusercontent.com/38065/92199117-19ad1780-ee2b-11ea-86ca-21fb937348ea.png)

2020-09-04 04:40 UTC, agliga commented
> Updates look good, but for some reason the first few examples don't have the ARIA attributes:
> 
> ![Screen Shot 2020-09-03 at 9 18 31 PM](https://user-images.githubusercontent.com/38065/92199117-19ad1780-ee2b-11ea-86ca-21fb937348ea.png)
This is because I added a condition to not add `role=group` and `aria-describeby` if there is not `a11yText` or header text. Otherwise theres nothing to point `aria-labelledby` to and I thought that those two attributes dont work without aria-labelledby

2020-09-04 15:46 UTC, ianmcburnie commented
I see what you mean. I think role="group" and aria-roledescription="Carousel" can be ever present, but as you say for continuous case, the aria-labelledby will only be added when dev adds `a11y-heading-text` and `a11y-heading-tag`.

Oops, and yes I should be enjoying the day off, so please ignore this until next week ;-)

2020-09-04 15:53 UTC, agliga commented
> I see what you mean. I think role="group" and aria-roledescription="Carousel" can be ever present, but as you say for continuous case, the aria-labelledby will only be added when dev adds `a11y-heading-text` and `a11y-heading-tag`.
> 
> Oops, and yes I should be enjoying the day off, so please ignore this until next week ;-)

Done, and yes you should check this next week :+1:

2020-09-08 22:45 UTC, ianmcburnie approved these changes

2020-09-08 23:26 UTC, merged