fix: reset ebay-select on form reset
eBay/ebayui-core pull request #1727
Opened 2022-08-12 23:33 UTC by LuLaValva

- Fixes #1714 

## Description
The `ebay-select` component did not reset when the form it was wrapped in received a "reset" event. This has been fixed.

2022-08-15 15:47 UTC, agliga approved these changes
Good job, simple and works well.

2022-08-15 15:55 UTC, ArtBlue approved these changes
Very nice! The simplicity is eloquent.

2022-08-15 18:22 UTC, ianmcburnie commented on src/components/ebay-select/examples/08-in-form/template.marko
> +    &nbsp
Remove this line. Will cause issues in actual code.

2022-08-15 18:28 UTC, ianmcburnie commented
This is setting selected back to the first value. What happens when there is a `selected` value? Both for server rendered and client rendered.

2022-08-16 16:18 UTC, agliga requested changes
We should first verify how to get the default value set. Usually when `selected` is set it forces  that to be the default value. 
What we can do:
We should have a default value saved `onMount`. (Uses should also be able to pass that default value in case they want to change it). That should be the reset value.

So we can do:
```
<ebay-select>
   <@option selected default-value>Option1</>
   <@option>Option2</>
</ebay-select>
```
And then either find what the default-value is onMount or use the currently selected one as the default value. Then when the reset is triggered it should select that element.

2022-08-16 23:50 UTC, LuLaValva commented
I've pushed a fix that chooses the first option selected as the default value. Including a `default-value` attribute seems to be outside the scope of this issue since `ebay-select` doesn't currently have that as a feature. Would you like me to add it anyway?

2022-08-17 00:32 UTC, agliga commented
> I've pushed a fix that chooses the first option selected as the default value. Including a `default-value` attribute seems to be outside the scope of this issue since `ebay-select` doesn't currently have that as a feature. Would you like me to add it anyway?

I think the issue is if the component gets unmounted and remounted then it might change the default selected value. 
It should be pretty easy to add that

2022-08-17 19:11 UTC, agliga approved these changes

2022-08-17 19:13 UTC, merged