1693 disable individual options
eBay/ebayui-core pull request #1760
Opened 2022-09-16 23:55 UTC by LuLaValva

- Fixes #1693 
- Fixes #1757 

### DEPENDENCIES
These changes have no effect until the following are published:
- Depends on ebay/skin#1870
- Depends on makeup/makeup-js#88

## Description
- Adds `aria-disabled` role to `ebay-listbox` and `ebay-filter-menu` when an item is disabled.

2022-10-04 19:57 UTC, LuLaValva commented on src/components/ebay-filter-menu/index.marko
> +                    aria-disabled=item.disabled && "true"
Ok, I added some parentheses. Thanks.

2022-10-06 17:25 UTC, agliga requested changes
Since we're touching these files, I want to flatten the examples directory for each component. The idea is when we touch an example, or test, let's use the new syntax.

So the new proposed syntax would be:
```
examples/disabled-with-label.marko
examples/with-label.marko
examples/base.marko
```
The old syntax where we had nested directories was used before we had storybook so we could display those in order. But with storybook it's not needed. It's easier to have examples all in 1 directory rather than multiple nested directories.

Also we should be taking some snapshot tests for these templates using storybook mocks (See my textbox PR https://github.com/eBay/ebayui-core/pull/1784). Don't worry about the browser tests for now, those can be complicated to convert to using storybook mock.

2022-10-14 21:47 UTC, agliga approved these changes

2022-10-14 22:02 UTC, ianmcburnie approved these changes

2022-10-14 22:04 UTC, merged