WIP: feat: add “form” variant to listbox-button
eBay/ebayui-core pull request #1823
Opened 2022-12-02 18:41 UTC by tigt

## Description
Add plumbing so skin gets a styling hook for `<listbox-button variant="form">`.

Marked as Draft because I’m unfamiliar with matters of taste in ebayui-core — in particular, I dunno if I should test this in server, browser, or both?

## Context
I looked how the form variant was defined in `button`, and tried reapplying those codebits to `listbox-button`.

## References
https://github.com/eBay/ebayui-core/issues/1804

## Screenshots
As described by @agliga in the referenced issue, this adds an under-the-hood option that skin can use — as such, there are no visual differences.

2023-01-03 18:37 UTC, agliga commented
This looks great. 
Generally we begin with the skin portion because the class names might change. So we want to get that ironed out first before doing the component piece. 
The only change I would do is I would add a default value to variant, like `regular` or something. And then we should just do the check of: `class=[(input.variant === 'form' && 'listbox-button--form')]`

2023-01-23 18:00 UTC, ArtBlue requested changes

2023-01-23 19:04 UTC, ArtBlue approved these changes
Nice!

2023-01-23 19:29 UTC, ArtBlue commented
Looks good to merge. Maybe just change the title of the PR?

2023-01-23 19:43 UTC, merged