feat: add localized formatting using date-fns
eBay/ebayui-core pull request #2160
Opened 2024-04-22 16:10 UTC by LuLaValva

## Description

Use `date-fns` to localize date format in date textbox instead of using ISO.

### Note
`date-fns` maintains _their own_ list of locales that likely doesn't exactly match the browser. This is likely something we will need to maintain ourselves, or provide/find a mapping

## Screenshots

<img width="303" alt="image" src="https://github.com/eBay/ebayui-core/assets/26027232/53c2d70a-f244-4d45-a0d8-49ac169e0c97">
<img width="258" alt="image" src="https://github.com/eBay/ebayui-core/assets/26027232/327916fa-6f7b-4750-98ce-64081d232b09">

2024-04-30 16:29 UTC, agliga requested changes
Please update from master. Lets try to get this in a patch but lets fix conflicts first.

2024-04-30 16:38 UTC, LuLaValva commented
I'll update from master, but I think this should be part of at least a minor version since placeholder text will need to be updated in applications that are using the component.

2024-04-30 16:57 UTC, LuLaValva commented
This is actually nontrivial for teams, since the placeholder needs to switch from being unconditionally `YYYY-MM-DD` to a localized format like `MM/DD/YYYY` for each locale. Alternatively, the placeholder can be removed or replaced with something like `Date`

2024-05-01 17:22 UTC, agliga commented
> This is actually nontrivial for teams, since the placeholder needs to switch from being unconditionally `YYYY-MM-DD` to a localized format like `MM/DD/YYYY` for each locale. Alternatively, the placeholder can be removed or replaced with something like `Date`

So for now: lets not make this automatic. If they want to get this new functionality, have them pass a flag like `auto-localize=true`. 
Next major version we will remove that flag and have it turn on by default.

2024-05-07 16:58 UTC, agliga commented on src/components/ebay-date-textbox/index.marko
> +    inputPlaceholderText = "MM/DD/YYYY",
We should probably keep the original default, otherwise it will be breaking if they don't pass in `localizeFormat`

2024-05-08 23:37 UTC, agliga approved these changes
Approving for now if that placeholder issue is fixed.

2024-05-15 21:38 UTC, agliga commented
Need to update snapshots in tests. @LuLaValva

2024-05-16 18:22 UTC, agliga approved these changes

2024-05-24 00:45 UTC, agliga commented
LGTM overall codewise
I see a couple of bugs.

In `localized` we should use `localizedFormat` by default. We should also update the placeholder there. That said, could we have the placeholder be automatically generated from the formatter?
Also theres a bad bug if I type in a bad date using dashes for example, it removes all the content. We should not select a date in that case but never remove the value of the textfield.

2024-05-24 22:29 UTC, merged