fix(date-textbox): ensure order and add disabled state
eBay/ebayui-core pull request #2166
Opened 2024-05-03 15:49 UTC by LuLaValva

## Description

- Add disabled state
- Ensure that date range is always in the correct order, even when entered manually

## Screenshots

<img width="446" alt="image" src="https://github.com/eBay/ebayui-core/assets/26027232/7ec823dc-eee5-4d8e-aa53-bcffea466dbf">

2024-05-06 16:55 UTC, LuLaValva commented on src/components/ebay-date-textbox/date-textbox.stories.ts
> +                "Locale used for formatting dates and determining first day of the week. Defaults to `navigator.language`.",
Not necessarily, but it's a documentation change so I don't think it really warrants its own PR.

2024-05-07 16:35 UTC, agliga requested changes
I think there's a bad bug with this. 
If there's a date selected in both inputs and I type in a date after the second one then they swap. I think that creates a bad UX. 
My feeling in that case is that the second date should probably clear rather than swap. 

This case that we are trying to fix should only be applied when I use the calendar popover thingy.

2024-05-07 16:35 UTC, agliga commented on .changeset/nine-ligers-shop.md
> +Order preservation fix
Can we name this to be `date-textbox: order preservation fix`

2024-05-07 16:35 UTC, agliga commented on src/components/ebay-date-textbox/component.ts
> +            if (this.state.secondSelected && iso > this.state.secondSelected) {
I think there can be a cleaner way to do this. 
Lets first fix the issue with the date being swapped when typing manually. And then I will revisit this.

2024-05-08 23:37 UTC, agliga commented
Blocking issue for now until we get more feedback on how to approach this.

2024-06-21 15:57 UTC, closed without merging