fix(pagination): change default number of pages shown
eBay/ebayui-core pull request #2238
Opened 2024-08-27 15:57 UTC by LuLaValva

- Resolves #2235 

## Description

- Pagination currently defaults to show _every_ page during initial render and then decreases after a page width is found. This seems reasonable at first glance, but it is problematic when there is a large number of pages and the component is rendered on the server. 

## Context & Screenshots

- See attached issue

2024-08-29 23:05 UTC, agliga approved these changes

2024-08-29 23:27 UTC, agliga requested changes
Getting some test failures

2024-09-19 20:08 UTC, LuLaValva commented
Bonus change: Test failures are reported in a `__screenshots__` directory, which should never be committed, so I added to `.gitignore`

2024-09-19 21:34 UTC, agliga approved these changes

2024-09-19 21:34 UTC, merged