feat(table): replaced column-type of "row-header" with boolean row-header
eBay/ebayui-core pull request #2355
Opened 2024-12-24 14:59 UTC by WinkeeFace

## Description

Replaced `column-type` of `row-header` with a boolean `row-header` in the `ebay-table` component. Updated the relevant Marko and JSON files to reflect this change.

## Context

This change was made to simplify the handling of row headers and improve ARIA accessibility. The boolean `row-header` is more intuitive and aligns better with accessibility standards.

## References

- Issue: [#2313](https://github.com/eBay/ebayui-core/issues/2313)

## Screenshots

N/A

2024-12-31 21:02 UTC, LuLaValva reviewed
Well done, thanks @WinkeeFace! Just a few notes:

1. Those tests are failing because you didn't include `rowHeader` in the `index.marko` destructure [here](https://github.com/eBay/ebayui-core/blob/master/src/components/ebay-table/index.marko#L4-L14).
2. Since Marko 5 / eBayUI normalizes kebab-case to camelCase so both are accepted, that needs to be accommodated for in TypeScript. To do this, you can either add duplicate `"row-header"?: boolean;` and `"column-type"?: ...` types in the interface (probably not recommended), or you can switch everything to kebab-case and use `WithNormalizedProps<>` like we do for `Input` (preferred).
3. `=true` is implied in Marko attributes (same as HTML), so there are a few examples that can be simplified (I showed one example in a code comment)

2024-12-31 21:02 UTC, LuLaValva commented on src/components/ebay-table/examples/default.marko
> +    <@header row-header=true>
```suggestion
    <@header row-header>
```

2024-12-31 21:56 UTC, WinkeeFace commented
> Well done, thanks @WinkeeFace! Just a few notes:
> 
> 1. Those tests are failing because you didn't include `rowHeader` in the `index.marko` destructure [here](https://github.com/eBay/ebayui-core/blob/master/src/components/ebay-table/index.marko#L4-L14).
> 2. Since Marko 5 / eBayUI normalizes kebab-case to camelCase so both are accepted, that needs to be accommodated for in TypeScript. To do this, you can either add duplicate `"row-header"?: boolean;` and `"column-type"?: ...` types in the interface (probably not recommended), or you can switch everything to kebab-case and use `WithNormalizedProps<>` like we do for `Input` (preferred).
> 3. `=true` is implied in Marko attributes (same as HTML), so there are a few examples that can be simplified (I showed one example in a code comment)

Thank you for the feedback! I'll make those corrections.

2025-01-10 13:16 UTC, LuLaValva commented
@WinkeeFace I appreciate the effort of going through and adding `as const`, but as I mentioned offline this will be fixed in the next version of `@marko/type-check`. Please undo these commits or remove the `as const` changes, we are hoping to have eBayUI updated today

2025-01-14 16:59 UTC, agliga requested changes
Please remove the `.DS_Store` files
You can add them to gitignore (which they should be there already)

2025-01-15 20:14 UTC, WinkeeFace commented
### **Additional Update: Remove `aria-pressed` from `ebay-table`**

This PR has been updated to address an additional issue:

#### **Description**
The `aria-pressed` attribute was incorrectly applied in the `ebay-table` component. This update removes its usage to ensure compliance with ARIA standards and accessibility best practices.

#### **Changes Made**
- Removed the `aria-pressed` attribute from `ebay-table`.

#### **Checklist**
- [ ] `aria-pressed` removed from `ebay-table`.
- [ ] Verified no regressions in the `ebay-table` component.
- [ ] Updated tests to reflect the removal of `aria-pressed`.

2025-01-17 03:35 UTC, closed without merging