feat(ebay-accordion): new component
eBay/ebayui-core pull request #2357
Opened 2024-12-31 22:51 UTC by saiponnada

## Description

## Context

## References

## Screenshots

2025-01-09 15:55 UTC, agliga reviewed
So we have another change going through for this version where all items are now singular (this is mainly for fixing some issues that marko 4 introduced). So going forward all attribute tags should have the same name both in code and in input.
So change all the `input.items` to be `input.item` (but still an array)

2025-01-09 15:55 UTC, agliga commented on src/components/ebay-accordion/accordion.stories.ts
> +        items: {
I think going forward we want to keep these as singular
So it should be `item`

2025-01-09 15:55 UTC, agliga commented on src/components/ebay-accordion/component-browser.ts
> +    items?: Marko.AttrTag<
Change to singular

2025-01-09 15:55 UTC, agliga commented on src/components/ebay-accordion/marko-tag.json
> +    "@items <item>[]": {
Also this should be just `@item <item>[]`

2025-01-09 16:07 UTC, agliga commented
@saiponnada 
For the template, lets do this

```
$ const {
  item: items = []
} = input

<for|item| of=items></for>
```
That way we read `input.item` but we have it in code as `items`

2025-01-16 16:08 UTC, HenriqueLimas commented on src/components/ebay-accordion/component-browser.ts
> +        this.emit("toggle", {
Should the toggle event be triggered on the accordion? We could not have it and let the application adds on each detail. This will trigger twice for the auto collapse case (in case one is already open). Should we pass the index of the details that is being toggled to give more context?

```
onToggle({ open, index, originalEvent })
```

2025-01-16 22:49 UTC, saiponnada commented on src/components/ebay-accordion/component-browser.ts
> +        this.emit("toggle", {
Good catch, removed emitting the toggle event on accordion. I mean index works fine too, I am just being consistent with details for now.

2025-01-21 16:49 UTC, LuLaValva commented on src/components/ebay-accordion/index.marko
> +    item: items = [],
Ooh, I think I like that idea. More in-line with the semantic HTML that's happening under the hood.

2025-01-21 16:51 UTC, LuLaValva commented on src/components/ebay-accordion/index.marko
> +    item: items = [],
So then would it make sense to switch `text` to `@summary` within `@details`?

2025-01-21 17:16 UTC, agliga commented on src/components/ebay-accordion/index.marko
> +    item: items = [],
Possibly, although I think its easier just to put it in render body

2025-01-21 17:26 UTC, LuLaValva commented on src/components/ebay-accordion/index.marko
> +    item: items = [],
Well, render body would still be reserved for the actual body of the `<details>`.

So
```marko
<@item text="Item 1" open>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</@item>
```
transforms to
```marko
<@details open>
    <@summary>Item 1</@summary>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</@details>

2025-01-21 17:41 UTC, HenriqueLimas commented on src/components/ebay-accordion/index.marko
> +    item: items = [],
On React we are using `<EbayDetails>` directly, so they will be aligned with a similar api https://github.com/eBay/ebayui-core-react/pull/402/files#diff-3b59444a042558e982d588089681d497268640fc8d3c2f21a35fa64a460eda23R37

2025-01-21 17:44 UTC, HenriqueLimas commented on src/components/ebay-accordion/index.marko
> +                on-toggle("handleToggle")
I think this is going to be part of the `...item` in case the app uses it.

2025-01-21 17:47 UTC, saiponnada commented on src/components/ebay-accordion/index.marko
> +    item: items = [],
I like the detail summary suggestion, looks nice to see it.

2025-01-21 17:48 UTC, LuLaValva commented on src/components/ebay-accordion/index.marko
> +                on-toggle("handleToggle")
@HenriqueLimas in Marko 5 event handlers aren't spread, so each one needs to be spelled out individually. This will be changing in Marko 6 for alignment with other frameworks.

2025-01-21 21:08 UTC, HenriqueLimas commented on src/components/ebay-accordion/index.marko
> +                on-toggle("handleToggle")
Oops! Thanks, that make sense.

2025-01-23 04:42 UTC, saiponnada commented on src/components/ebay-accordion/index.marko
> +                on-toggle("handleToggle")
Done.

2025-01-23 19:26 UTC, ArtBlue approved these changes
Looks good

2025-01-23 19:35 UTC, agliga requested changes
Looks good
But we should be toggling things using markos way of toggling things rather than dom manipulation

2025-01-23 19:35 UTC, agliga commented on src/components/ebay-accordion/component-browser.ts
> +        const index = detailsElements.indexOf(
This shouldn't be needed
We can pass in index from the template directly into this function.

2025-01-23 19:35 UTC, agliga commented on src/components/ebay-accordion/component-browser.ts
> +        if (autoCollapse && event.open) {
Might be better to set a state variable with the index and if the index doesnt match then set open to false in template.

2025-01-24 15:37 UTC, agliga approved these changes

2025-01-24 16:15 UTC, merged